database:
  file: lovehunt.db
  pool-size: 4

performance:
  autosave-minutes: 5
  command-cooldown-ms: 700
  compass-update-seconds: 8

creation:
  material: EMERALD
  amount: 1
  duration-days: 7
  same-target-cooldown-days: 3
  target-min-account-age-days: 3
  max-active-by-player: 5

  reward-source: HAND # HAND or CONFIG
  default-reward:
    material: EMERALD
    amount: 64
  minimum-reward:
clan-bounty:
  enabled: true
  max-targets: 10
  per-player-cooldown-hours: 24
  duration-days: 7

server-bounty:
  max-hunters: 25

gui:
  main-title: "<dark_gray>LoveHunt"
  all-title: "<dark_gray>Все розыски"
  mine-title: "<dark_gray>Мои розыски"
  confirm-create-title: "<dark_gray>Подтверждение заказа"
  confirm-accept-title: "<dark_gray>Принять розыск"
  items:
    filler: BLACK_STAINED_GLASS_PANE
    all-bounties: COMPASS
    my-bounties: PLAYER_HEAD
    create-bounty: WRITABLE_BOOK
    sort: NAME_TAG
    price: GOLD_NUGGET
    type-filter: COMPASS
    clan-filter: SHIELD
    online-filter: ENDER_EYE
    reset: BARRIER
    search: OAK_SIGN
    previous: ARROW
    next: ARROW
    back: ARROW
    confirm: LIME_CONCRETE
    cancel: RED_CONCRETE
    cancel-order: RED_CONCRETE

heads:
  use-base64-for-buttons: false
  all-bounties-base64: ""
  my-bounties-base64: ""
  create-bounty-base64: ""
  sort-base64: ""
  price-base64: ""
  type-filter-base64: ""
  clan-filter-base64: ""
  online-filter-base64: ""
  search-base64: ""
  reset-base64: ""
  previous-base64: ""
  next-base64: ""
  back-base64: ""
  cancel-order-base64: ""
